apiVersion: v1
kind: Service
metadata:
  name: local-dev-example
  labels:
    app.kubernetes.io/name: local-dev-example
    app.kubernetes.io/instance: local-dev-example
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http

#    - port: 81
#      targetPort: 40000
#      name: debug

  selector:
    app.kubernetes.io/name: local-dev-example
    app.kubernetes.io/instance: local-dev-example

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-dev-example
  labels:
    app.kubernetes.io/name: local-dev-example
    app.kubernetes.io/instance: local-dev-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: local-dev-example
      app.kubernetes.io/instance: local-dev-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: local-dev-example
        app.kubernetes.io/instance: local-dev-example
    spec:
      serviceAccountName: local-dev-example
      containers:
        - name: local-dev-example
          image: local-dev-example
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
#            - containerPort: 40000
#              name: debug
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-dev-example
  namespace: default