apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: skaffoldebug
build:
  artifacts:
  - image: local-dev-example
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s.yaml
