apiVersion: skaffold/v2beta11
kind: Config
#  Config
metadata:
  name: skaffoldebug

build:
  artifacts:
  - image: skaffoldebug
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: "skaffoldebug"
        chartPath: deployment/helm/skaffoldebug
        artifactOverrides:
          image: skaffoldebug
#  kubectl:
#    manifests:
#    - k8s.yaml
