apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.http.servicePort }}
      targetPort: {{ .Values.http.containerPort }}
      name: {{ .Values.http.name }}

  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}

